# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Second Prompt Test"

prompts:
  - "Answer the following question: {{question}}"
  - "Answer the following question. This is very important to my career!: {{question}}"
  - "You are an expert Astronomer. Answer the following question: {{question}}"
  - "Answer the following question. Let's think step-by-step: {{question}}"

  

providers:
  - id: "openai:gpt-4o-mini"
    config:
      temperature: 1.0
      max_tokens: 1000
      apiKeyEnvar: OPENAI_API_KEY
  

tests:
  - vars:
      question: What is true for a type-Ia ("type one-a") supernova? (A) This type occurs in binary systems. (B) This type occurs in young galaxies. (C) This type produces gamma-ray bursts. (D) This type produces high amounts of X-rays.

    assert:
      - type: llm-rubric
        value: Identifies answer as (A)
        provider: openai:gpt-4o-mini
